$(document).ready(function(){


var headercontent = $('<div class="top">'
            + '<div class="container">'
                + '<div class="row">'
                    + '<div class="col-sm-6">'
                       + ' <p><img src="img/top_logo.jpg"></p>'
                    + '</div>'
               + ' </div>'
            + '</div>'
       + ' </div>'
+ '<nav class="navbar navbar-expand-md navbar-light bg-light navbar-default">'
 + ' <!--<a class="navbar-brand pb-2" href="#">Navbar</a>'
  + '<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">'
    + '<span class="navbar-toggler-icon"></span>'
  + '</button> -->'
	+ '<div class="container">'
+ '<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarNavDropdown"><span class="sr-only">Toggle Navigation</span><img src="img/menu.png"></button>'
+ '<a href="index.html" class="navbar-brand"><img src="img/logo.png" alt="Post"></a>'
  + '<div class="collapse navbar-collapse" id="navbarNavDropdown">'
   + ' <ul class="nav navbar-nav">'
     + ' <li class="nav-item dropdown">'
       + '<a class="nav-link dropdown-toggle" href="introduction.html" id="navbarDropdownMenuLink" data-hover="dropdown" aria-haspopup="true" aria-expanded="false">'
		+ 'Introduction  <span class="caret"></span>'
	+ '</a>'
	+ '<ul class="dropdown-menu dropdownhover-bottom" aria-labelledby="navbarDropdownMenuLink">'
         + ' <li><a class="dropdown-item" href="getstarted.html">Get Started</a></li>'
         + ' <li><a class="dropdown-item" href="designprinciples.html">Design Principles</a></li>'
          + '<li><a class="dropdown-item" href="bestpractices.html">Best Practices</a></li>'
          + '<li><a class="dropdown-item" href="rolesandresponsibilities.html">Roles and Responsibilities</a></li>'
        + '</ul>'
      + '</li>'
      + '<li class="nav-item dropdown">'
        + '<a class="nav-link dropdown-toggle" href="design.html" id="navbarDropdownMenuLink" data-hover="dropdown" aria-haspopup="true" aria-expanded="false">'
         + ' Design <span class="caret"></span>'
        + '</a>'
       + ' <ul class="dropdown-menu dropdownhover-bottom" aria-labelledby="navbarDropdownMenuLink">'
         + ' <li class="dropdown"><a class="dropdown-item dropdown-toggle" href="#">Element</a>'
           + ' <ul class="dropdown-menu dropdownhover-left">'
            + '  <li><a class="dropdown-item" href="HDBcorporatesignature.html">HDB Corporate Signature</a></li>'
             + ' <li><a class="dropdown-item" href="backgroundandplacement.html">Background and Placement</a></li>'
             + ' <li><a class="dropdown-item" href="gridsystem.html">Grid System</a></li>'
             + ' <li><a class="dropdown-item" href="typography.html">Typography</a></li>'
             + ' <li><a class="dropdown-item" href="#">Favicon</a></li>'
             + ' <li><a class="dropdown-item" href="imagery.html">Imagery</a></li>'
             + ' <li><a class="dropdown-item" href="colors.html">Colors</a></li>'
             + ' <li><a class="dropdown-item" href="minimumclearspace.html">Clear Space</a></li>'
             + ' <li><a class="dropdown-item" href="workflow.html">Workflow</a></li>'
             + ' <li><a class="dropdown-item" href="applicationsecurity.html">Application Security</a></li>'
             + ' <li><a class="dropdown-item" href="systemavailability.html">System Availability</a></li>'
           + ' </ul>'
         + ' </li>'
         + ' <li class="dropdown"><a class="dropdown-item dropdown-toggle" href="#">Components</a>'
           + ' <ul class="dropdown-menu dropdownhover-left">'
             + ' <li><a class="dropdown-item" href="accordian.html">Accordian</a></li>'
              + '<li><a class="dropdown-item" href="banner.html">Banner</a></li>'
              + '<li><a class="dropdown-item" href="breadcrumbs.html">Breadcrumbs</a></li>'
              + '<li><a class="dropdown-item" href="buttonsandnavigations.html">Buttons</a></li>'
              + '<li><a class="dropdown-item" href="dropdown.html">Dropdown</a></li>'
             + ' <li><a class="dropdown-item" href="errormessages.html">Error Messages</a></li>'
             + ' <li><a class="dropdown-item" href="formselements.html">Forms Elements</a></li>'
             + ' <li><a class="dropdown-item" href="glossarizer.html">Glossarizer</a></li>'
              + '<li><a class="dropdown-item" href="iconlibrary.html">Icons Library</a></li>'
             + ' <li><a class="dropdown-item" href="inputs.html">Inputs</a></li>'
             + ' <li><a class="dropdown-item" href="launchpad.html">Launch Pad</a></li>'
             + ' <li><a class="dropdown-item" href="link.html">Link</a></li>'
	     + ' <li><a class="dropdown-item" href="list.html">List</a></li>'
             + ' <li><a class="dropdown-item" href="madlibs.html">Madlibs</a></li>'
              + '<li><a class="dropdown-item" href="#">Modal</a></li>'
              + '<li><a class="dropdown-item" href="navigations.html">Navigations</a></li>'
              + '<li><a class="dropdown-item" href="#">Pagination</a></li>'
              + '<li><a class="dropdown-item" href="radiobuttons.html">Radio Buttons</a></li>'
              + '<li><a class="dropdown-item" href="slider.html">Slider</a></li>'
              + '<li><a class="dropdown-item" href="tables.html">Tables</a></li>'
            + '</ul>'
          + '</li>'
        + '</ul>'
      + '</li>'
      + '<li class="nav-item dropdown">'
        + '<a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-hover="dropdown" aria-haspopup="true" aria-expanded="false">'
          + 'Governance <span class="caret"></span>'
        + '</a>'
        + '<ul class="dropdown-menu dropdownhover-bottom" aria-labelledby="navbarDropdownMenuLink">'
          + '<li><a class="dropdown-item" href="digitalgovernmentblueprint.html">Digital Government Blueprint</a></li>'
          + '<li><a class="dropdown-item" href="digitalservicesstandards.html">Digital Services Standards</a></li>'
        + '</ul>'
      + '</li>'
      + '<li class="nav-item dropdown">'
        + '<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-hover="dropdown" aria-haspopup="true" aria-expanded="false">'
         + ' UX <span class="caret"></span>'
        + '</a>'
        + '<ul class="dropdown-menu dropdownhover-bottom" aria-labelledby="navbarDropdownMenuLink">'
          + '<li class="dropdown"><a class="dropdown-item dropdown-toggle" href="userresearch.html">User Research</a>'
           + ' <ul class="dropdown-menu dropdownhover-left">'
             + ' <li><a class="dropdown-item" href="empathymap.html">Empathy Map</a></li>'
             + ' <li><a class="dropdown-item" href="customerjourneymapping.html">Customer Journey Mapping</a></li>'
             + ' <li><a class="dropdown-item" href="interview.html">Interview</a></li>'
             + ' <li><a class="dropdown-item" href="fieldstudies.html">Field Studies</a></li>'
            + '</ul>'
          + '</li>'
           + '<li class="dropdown"><a class="dropdown-item dropdown-toggle" href="designevaluation.html">Design Evaluation</a>'
           + ' <ul class="dropdown-menu dropdownhover-left">'
             + ' <li><a class="dropdown-item" href="uxteardown.html">UX Teardown</a></li>'
             + ' <li><a class="dropdown-item" href="heuristicevaluation.html">Heuristic Evaluation</a></li>'
             + ' <li><a class="dropdown-item" href="cognitivewalkthrough.html">Cognitive Walkthrough</a></li>'
           + ' </ul>'
          + '</li>'
          + '<li class="dropdown"><a class="dropdown-item dropdown-toggle" href="#">Web Analytics</a>'
            + '<ul class="dropdown-menu dropdownhover-left">'
             + ' <li><a class="dropdown-item" href="overview.html">Overview</a></li>'
              + '<li><a class="dropdown-item" href="eventstracking.html">Events Tracking</a></li>'
             + ' <li><a class="dropdown-item" href="goals.html">Goals</a></li>'
             + ' <li><a class="dropdown-item" href="funnelvisualisation.html">Funnel Visualisation</a></li>'
            + '</ul>'
         + ' </li>'
       + ' </ul>'
     + ' </li>'
    + '</ul>'
  + '</div>'
+ '</div>'
+ '</nav>');

$("#header").append(headercontent);        
});